version: '3'
services:
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    nginx :
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        environment:
            - REDIS_HOST=192.168.99.100
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=192.168.99.100
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5342
    client:
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
    
        
        